export interface Fornecedor{
    ID : number,
    TipoPessoa : any,
    NumDoc : string,
    Nome : string,
    RazaoSocial : string,
    InscEstadual : string,
    CEP : string,
    Endereco : string,
    Complemento : string,
    Bairro : string,
    Cidade : string,
    UF : string,
    Telefone : string,
    Celular : string,
    Whatsapp : any,
    Email : string,
    NomeContato : string,
    Obs : string,
    DtCadastro : Date,
    IDUsuCadastro : number,
    Ativo : any,
    NomeUsuCadastro: string    
}